name: example
description: Example module following nf-core standards
keywords:
    - example
    - template
tools:
    - example:
          description: Example tool for demonstration purposes
          homepage: https://github.com/bigbio/nf-modules
          documentation: https://github.com/bigbio/nf-modules
          licence: ["MIT"]
input:
    - meta:
          type: map
          description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
    - input_file:
          type: file
          description: Input file to process
          pattern: "*"
output:
    - meta:
          type: map
          description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
    - output:
          type: file
          description: Output file
          pattern: "*.output"
    - versions:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
    - "@bigbio"
maintainers:
    - "@bigbio"
